# Site settings
title: Bobs Blog
description: 'Random thoughts from many of my personalities...'
url: 'https://brobertsaz.github.io/blog/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bob Roberts'
  email: cardsfanbob@gmail.com
  twitter_username: bobr_az
  github_username:  brobertsaz
  linkedin_username:  bobrobertsror

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
